[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_shield_sdk = "33eJhB9P4Kmf51MUpRgpJpdDab2MWP9FmpVHrASspJ3B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/congdm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
